### ISSUE TITLE
Strange characters

### ISSUE THREAD

**Issue by sarsey-walker** [catppuccin/yazi#9]
I was setting yazi on my ubuntu, but could not make whatever this characters are. Is it supposed to be like this?
I've installed all the nerd fonts and tried find the hex code but nothing matches.

![image](https://github.com/user-attachments/assets/58f9e1a4-4e79-49ef-a0dc-1cb46782512c)
![image](https://github.com/user-attachments/assets/b1e4e3f6-51cb-4c80-98bc-2e5e50a9c5e3)

**Comment by uncenter** [comment]
Those are nerd font icons!

**Comment by sarsey-walker** [comment]
After A LOT of tests i figured out what was wrong. I was not using the right font on my terminal!
It happened that I chose a font that didn't have or didn't support these icons!

Thanks though. I was convinced that the problem was on the server, not on the host.
